
branches:
  only:
    - master

image: Visual Studio 2019

services:
  - mssql

platform: Any CPU

configuration:
  - Debug
  - Release
  
before_build:
  - nuget restore

build:
  project: MarathonManager.sln

test:
  only:
  - Core.Test.dll