
branches:
  only:
    - master

image: Visual Studio 2017

services:
  - mssql2014

platform: Any CPU

configuration:
  - Debug
  - Release
  
before_build:
  - nuget restore

build:
  project: MarathonManager.sln
